### ISSUE TITLE
CRDB now has an official Python package

### ISSUE THREAD

**Issue by HDembinski** [kkrings/crspectra#6]
As of today, CRDB has an official package:
https://pypi.org/project/crdb/

Since v4.0 released in 2020, the CRDB also officially contains data from air shower observatories. The official CRDB Python package should then cover the same content as your crspectra package.

**Comment by kkrings** [comment]
That's awesome! Thanks for reaching out to me. I'm more than happy to mark my package as deprecated and referring to the official package instead.

**Comment by kkrings** [comment]
The `crspectra` package is now declared as deprecated.
